### ISSUE TITLE
Usage example ETA?

### ISSUE THREAD

**Issue by lifenautjoe** [scriptwerx/angular-egg#2]
I would like to see a full working example of the directive, is there any estimated time? Planning on using it in a 100% Angular project that involves 8+ developers, need to provide them a usage reference.

**Comment by theDustRoom** [comment]
I'm not sure I understand your question on estimated time?

The directive is very easy to use; there's a working plunkr referenced here:
[here](https://github.com/scriptwerx/angular-egg/issues/1)

**Comment by lifenautjoe** [comment]
I saw on the README

> We'll create a fully working demo as soon as possible and update the
> build.

The provided link does it anyway. Thanks.

**Comment by theDustRoom** [comment]
Ah yes; just been too busy to do it I'm afraid.
