### ISSUE TITLE
Doesn't always fire & double include

### ISSUE THREAD

**Issue by geoguide** [scriptwerx/angular-egg#3]
Sometimes, especially if i've already done something on the page it does not fire when I type in the code. It doesn't throw any errors, the div just does not show up.

Also when I installed via bower, everytime it compiles it includes both angular-egg.js and angular-egg.min.js

Why is that? Is it from the bower.json?

**Comment by theDustRoom** [comment]
Hi geoguide.

I've put together a quick demo on jsfiddle http://jsfiddle.net/scriptwerx/m24nfpjr/ and updated the README with the link.

No matter how much I use the "app" it always fires ok.

Which version of Angular are you using with it?

Not sure why it's including both files - what are you using for your build process and how is it configured?

**Comment by geoguide** [comment]
Hello. I am using it with angular 1.3.18

I have it configured this way in my bower:     "angular-egg": "~0.0.5", I run grunt via the official yeoman angular generator.

One of the people using my app can never get it to fire. Sometimes if I refresh, and then start type it in immediately it works after it does not work.

Edit: FWIW I'm looking at angular jwt's bower file. They have both a .js and a .min.js but show this: http://grab.by/Lq68 If I change the bowerfile in the egg library to be one of the two it loads only that one into my index when i run grunt.

Edit2: They are the same issue. If I remove the redundant script it fires every time. Thanks :)

**Comment by theDustRoom** [comment]
I've updated the build to v0.0.6 which should fix your double include issue.
